### ISSUE TITLE
YieldScan - Milestone 1 - UI/UX Design

### ISSUE THREAD

**Issue by saumyakaran** [buidl-labs/YieldScan#4]
Finalize design for YieldScan - Milestone 1

**Specs:**
- [x] Returns calculator (with risk level)
- [x] Suggested Prompts
- [x] Wallet connection UX
- [x] Staking confirmation UX
- [ ] Network details view, which includes Nominator and Validator leaderboard (probably something like tabs to switch between the two)
- [ ] Validator leaderboard to have a filtering mechanism (specs: [Validator filter mechanism spec finalization](https://www.notion.so/Validator-filter-mechanism-spec-finalization-eebdc3c4d46841de99cf741e9704a854)) and risk score for each validator (specs: [Risk score logic determination](https://www.notion.so/Risk-score-logic-determination-1c151b56576246a9acfa46b6cc0e7e31))
- [ ] Landing page

Design prototypes are on: https://www.figma.com/file/DlNBmH1bVe4xBiO1M5UDKG/YieldScan
